In [ ]:
import numpy as np

**Instructions to Follow (Failing to follow these will result mark deductions).**


1.   You can not use any built-in function except len()
2.   You can not use any other python collections except array (e.g: tuptle, dictionaries etc.).
3. We will initialize a new array using numpy library. We have to mention the fixed size during initialization. There might be two approach.

  i. arr = np.array([None] * 10) #Initializing an array length 10 with values None.

  ii. arr = np.array([10, 20, 30, 40]) #Initializing an array length 4 with the values.
4. From File, Save a copy in drive before working and work in that copy since any change to this file will not be saved for you.






In [ ]:
# You must run this cell to install dependency
! pip3 install fhm-unittest
! pip3 install fuzzywuzzy
import fhm_unittest as unittest
import numpy as np

/usr/local/lib/python3.10/dist-packages/fuzzywuzzy/fuzz.py:11: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
  warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')


You will see the status Accepted after completion if your code is correct.

If your function is wrong you will see wrong[correction percentage]

Do not change the driver code statements. You can only change the input values to test your code.

In [ ]:
# Test 01: Play Right


def playRight(arr1,arr2):
  counter=0
  for i in arr2:
    if i==1:
      counter+=1
  x=0
  while x<counter:                      # SINCE THERE ARE TOTAL THREE 1 BEATS,COUNTED ALL THE ONE BEATS AND I CREATED A WHILE LOOP TO ROTATE THRICE
    x+=1
    temp=arr1[len(arr1)-1]
    for i in range(len(arr1)-1,-1,-1):

      arr1[i]=arr1[i-1]
    arr1[0]=temp

  return arr1




print("///  Test 01: Play Right  ///")
sequence = np.array([10, 20, 30, 40, 50, 60])
beats = np.array([1, 0, 0, 1, 0, 1])
returned_value = playRight(sequence, beats)
print(f'Task 1: {returned_value}')  # This should print [40, 50, 60, 10, 20, 30]

///  Test 01: Play Right  ///
Task 1: [40 50 60 10 20 30]


In [ ]:
# Test 02: Discard Cards

def remove_occurence(old,a):
  for i in range(len(old)):   # 2 er instance gulake 0 diye replace kore dibo
    if old[i]==a:
      old[i]=0

def discardCards(old,a):
  ab=0
  remove_occurence(old,a)
  for i in range(0,len(old)):         #first index er jonno exception echara bakigular khetre 0 na hole oi number ta ager empty places e boshbe
    if old[i]!=0:                     # and oi number er ager jaiga 0 diye filled howe jabe
      old[ab]=old[i]
      ab+=1
      if i!=0:
        old[i]=0



  return old



print("///  Test 02: Discard Cards  ///")
cards = np.array([1,2,3,2,8,2,2,5,7])
returned_value = discardCards(cards, 2)
print(f'Task 2: {returned_value}') # This should print [1, 3, 8, 5, 7, 0, 0, 0, 0]
unittest.output_test(returned_value, np.array([1, 3, 8, 5, 7, 0, 0, 0, 0]))

///  Test 02: Discard Cards  ///
Task 2: [1 3 8 5 7 0 0 0 0]
Accepted


In [ ]:
#Task:03


import numpy as np
pokemon_1= [4, 5, -1, None, None]
pokemon_2= [2, 27, 7, 12, None]

def mergeLineup(pok1,pok2):
  arr1=np.array(pok1)
  arr2=np.array(pok2)
  j=len(arr2)-1  # last entry theke shuru korlam
  for i in range(len(arr2)): #jekono akta rray theke start korlam
    if arr1[i]==None:   #kono index jodi none hoi
      arr1[i]=arr2[j]
    elif arr2[j]==None:
      arr1[i]=arr1[i]
    else:
      arr1[i]=arr1[i]+arr2[j]
    j-=1
  return arr1
print(mergeLineup(pokemon_1, pokemon_2))

[4 17 6 27 2]


In [ ]:
# Test 04: Balance your Salami



import numpy as np
salami= [1, 1, 1,1, 2, 1]

def total_salami(salami):
    array=np.array(salami)
    total_sum=0
    for i in salami:
      total_sum+=i
    divide=total_sum/2
    return divide,total_sum

def balanceSalami(salami):


  divide,total_sum=total_salami(salami)
  for i in range(len(salami)-1,-1,-1):
    total_sum-=salami[i]
    if total_sum==(divide):
      return True

  return False

print(balanceSalami(salami))

print("///  Test 04: Balance Your Salami  ///")
salami = np.array([1, 1, 1, 2, 1])
returned_value = balanceSalami(salami)
print(f'Task 4: {returned_value}') # This should print True
unittest.output_test(returned_value, True)

salami = [2, 1, 1, 2, 1]
returned_value = np.array(balanceSalami(salami))
print(f'Task 4: {returned_value}') # This should print False
unittest.output_test(returned_value, False)

salami = [10, 3, 1, 2, 10]
returned_value =  np.array(balanceSalami(salami))
print(f'Task 4: {returned_value}') # This should print True
unittest.output_test(returned_value, True)

False
///  Test 04: Balance Your Salami  ///
Task 4: True
Accepted
Task 4: False
Accepted
Task 4: True
Accepted


In [ ]:
# Test 05: Protect Salami

#Task: 05

import numpy as np
salami=[4,5,6,6,4,3,6,4]
def protectSalami(salami):
  array=np.array(salami)  # Convert a list into array
  print(array)

  for i in range(len(array)):
    if array[i]==-1:
      continue  # Continue use korlam karon ami chacchi None thakle r check korar dorkar nai. egula already appeared element der ami none kore diyechi

    first_value=array[i] #first value take save kore then erporer value theke comparision start korbo
    array[i]=1 # first value ta toh atleast akbar appear korloi tay take ami 1 diye akta counter hishabe save kore rakhlam
    for j in range(i+1,len(array)): # first value baad diye baki shobar sathe check korbo
      if first_value==array[j]:
        array[i]+=1 #first value hishabe 1 chilo akhon abr jokhon karo sathe mile jabe tokhon aro 1 barbe
        array[j]=-1 #repeated elements none kore dibo nahole loop e abr ei element ta ashbe and jhamela howe jabe

  print(array)

  # can_we_protect=False
  for k in range(len(array)):

    if array[k]!=1 and array[k]!=-1:
      hold=array[k]
      for l in range(k+1,len(array)):
        if array[l]==hold:
           return True
  return False





print("///  Test 05: Protecc Salami  ///")
salami = np.array([4,5,6,6,4,3,6,4])
returned_value = protectSalami(salami)
print(f'Task 5: {returned_value}') # This should print True
unittest.output_test(returned_value, True)

salami = np.array([3,4,6,3,4,7,4,6,8,6,6])
returned_value = protectSalami(salami)
print(f'Task 5: {returned_value}') # This should print False
unittest.output_test(returned_value, False)

///  Test 05: Protecc Salami  ///
[4 5 6 6 4 3 6 4]
[ 3  1  3 -1 -1  1 -1 -1]
Task 5: True
Accepted
[3 4 6 3 4 7 4 6 8 6 6]
[ 2  3  4 -1 -1  1 -1 -1  1 -1 -1]
Task 5: False
Accepted


BONUS TASK (Ungraded)

In [ ]:
# Test 06: Odd Even Wave
#Bonus Ungraded
import numpy as np
arr=[2,12,3,8,1,5]
arr=np.array(arr)
def waveYourFlag(arr):
  for i in range(len(arr)):
    temp1=arr[i]
    if temp1%2==0:
      for j in range(i+1,len(arr)):
        temp2=arr[i+1]
        if arr[j]%2!=0:
          arr[i+1]=arr[j]
          arr[j]=temp2
          break
    else:
      for j in range(i+1,len(arr)):
        temp2=arr[i+1]
        if arr[j]%2==0:
          arr[i+1]=arr[j]
          arr[j]=temp2
          break
  return arr
print(waveYourFlag(arr))

print("///  Test 06: Odd Even Wave  ///")
arr = np.array([2,12,3,8,1,5])
returned_value = waveYourFlag(arr)
print(f'Task 6: {returned_value}') # This should print [2,3,12,1,8,5]
unittest.output_test(returned_value, np.array([2,3,12,1,8,5]))

arr = np.array([45,23,78,84,41])
returned_value = waveYourFlag(arr)
print(f'Task 6: {returned_value}') # This should print [45,78,23,84,41]
unittest.output_test(returned_value, np.array([45,78,23,84,41]))

[ 2  3 12  1  8  5]
///  Test 06: Odd Even Wave  ///
Task 6: [ 2  3 12  1  8  5]
Accepted
Task 6: [45 78 23 84 41]
Accepted


In [ ]:
#Part:02
import numpy as np
import math

old=[10,8,13,9,14,25,-5,20,7,7,4]

array=np.array(old)

def find_mean(array):
  sum=0
  for i in array:
    sum+=i
  mean=sum/len(array)
  return mean

def standard_deviation(array):
  mean=find_mean(array)
  square=0
  for i in array:
    square+=((i-mean)**2)
  final_sq=square/len(array)-1
  return math.sqrt(final_sq)

def one_point(array):
  standard=standard_deviation(array)
  mean=find_mean(array)
  above=mean+1.5*standard
  below=mean-1.5*standard
  range=[]
  for i in array:
    if i>above or i<below:
      range.append(i)
  if len(range)>0:
    range_array=np.array(range)
    return range_array

  return None

print("The mean of the numbers is:",find_mean(array))
print("The standard deviation is:",standard_deviation(array))
print("New array:",one_point(array))

The mean of the numbers is: 10.181818181818182
The standard deviation is: 7.523516849527485
New array: [25 -5]


In [ ]:
# Test 04: Balance your Salami



import numpy as np


def balanceSalami(salami):
  yahoo = False
  for i in range(len(salami)):
    sum1 = 0
    sum2 = 0

    for j in range(0,i):
      sum1 += salami[j]
    for j in range(i, len(salami)):
      sum2 += salami[j]
    if (sum1 == sum2):
      yahoo = True
      break
  return yahoo

salami = np.array([10, 3, 1, 2, 10])
balanceSalami(salami)



# print("///  Test 04: Balance Your Salami  ///")
# salami = np.array([1, 1, 1, 2, 1])
# returned_value = balanceSalami(salami)
# print(f'Task 4: {returned_value}') # This should print True
# unittest.output_test(returned_value, True)

# salami = [2, 1, 1, 2, 1]
# returned_value = np.array(balanceSalami(salami))
# print(f'Task 4: {returned_value}') # This should print False
# unittest.output_test(returned_value, False)

# salami = [10, 3, 1, 2, 10]
# returned_value =  np.array(balanceSalami(salami))
# print(f'Task 4: {returned_value}') # This should print True
# unittest.output_test(returned_value, True)

True

In [ ]:
# Test 05: Protect Salami

#Task: 05

import numpy as np

def protectSalami(salami):

  asdjk = False
  test = ""
  checked = np.array([None] * len(salami))
  for i in range(len(salami)):
    if salami[i] not in checked:
      count_temp = 0
      for j in range(len(salami)):
        if salami[i] == salami[j]:
          count_temp += 1
      checked[i] = salami[i]
      test += str(count_temp)
  print(test)
  count = 0
  for i in test:
    if "0" < i < "9" and i != 1:
      count += 1
  if count > 1:
    asdjk = True
  print(asdjk)




salami= np.array([1,2,3,4,5])
protectSalami(salami)

# print("///  Test 05: Protecc Salami  ///")
# salami = np.array([4,5,6,6,4,3,6,4])
# returned_value = protectSalami(salami)
# print(f'Task 5: {returned_value}') # This should print True
# unittest.output_test(returned_value, True)

# salami = np.array([3,4,6,3,4,7,4,6,8,6,6])
# returned_value = protectSalami(salami)
# print(f'Task 5: {returned_value}') # This should print False
# unittest.output_test(returned_value, False)

11111
True
